### ISSUE TITLE
New function for return object

### ISSUE THREAD

**Issue by rafaelgo1705** [savannabits/typeorm-pagination#5]
**Hello,** I would like to open a PR or suggest that this functionality be implemented in your library. I'm talking about the return of the last page number **(last_page)**. I've already done the implementation, it was just one more calculation, very basic. What is your opinion?

**Comment by coolsam726** [comment]
Hi @rafaelgo1705 , please go ahead to submit the PR and I will be glad to have a look. Thanks!

**Comment by rafaelgo1705** [comment]
I created a local branch to upload to github, but I don't have permission to publish.

Quando tento:
`git push --set-upstream origin calcule_last_page`

Retorna isso:
`remote: Permission to savannabits/typeorm-pagination.git denied to rafaelgo1705.
fatal: unable to access 'https://github.com/savannabits/typeorm-pagination.git/': The requested URL returned error: 403`

**Comment by coolsam726** [comment]
If I am not mistaken, you should first fork the repo, then implement your
request there, then submit a PR from your fork.

**Comment by rafaelgo1705** [comment]
Hello, I opened PR: https://github.com/savannabits/typeorm-pagination/pull/6. Thank you!

**Comment by coolsam726** [comment]
PR #6 is now published in v2.0.2. Thanks again for the contribution.
